### ISSUE TITLE
Add helper functions to check particle properties

### ISSUE THREAD

**Issue by tamasgal** [JuliaPhysics/Corpuscles.jl#19]
We already discussed this but somehow forgot to create an issue (let alone implement it 😉): helper functions like in the `particle` Python package, cf. https://github.com/scikit-hep/particle/blob/92610e8a73667b000906084a1bba3410ebc55d91/src/particle/particle/particle.py#L740 or https://github.com/scikit-hep/particle/blob/master/src/particle/pdgid/functions.py

Those helper functions are members of the `Particle` class or implemented in the `pdgid` submodule as simple functions of PDG IDs. For Julia we should rather go the functional way and focus on tiny helper functions which take `Particle` as input, like `is_meson(p::Particle)`.

Let's collect and implement those functions. Suggestions are welcome!

Here is a list of some of the functions `particle` provide. I think we should try to adhere the naming convention to increase the interchangeability:

- [x] `is_quark`
- [x] `is_lepton`
- [x] `is_hadron`
- [x] `is_meson`
- [x] `is_baryon`
- [x] `is_diquark`
- [x] `is_nucleus`
- [x] `is_pentaquark`
- [x] `is_gauge_boson_or_higgs`
- [x] `is_sm_gauge_boson_or_higgs`
- [x] `is_generator_specific`
- [x] `is_special_particle`
- [x] `is_Rhadron`
- [x] `is_Qball`
- [x] `is_dyon`
- [x] `is_SUSY`
- [x] `is_technicolor`
- [x] `is_composite_quark_or_lepton`
- [x] `has_down`
- [x] `has_up`
- [x] `has_strange`
- [x] `has_charm`
- [x] `has_bottom`
- [x] `has_top`
- [x] `has_fundamental_anti`
- [x] `charge`
- [x] `threecharge`
- [x] `A`
- [x] `Z`
- [x] `J`
- [x] `S`
- [x] `L`
- [x] `jspin`
- [x] `sspin`
- [x] `lspin`
- [x] `isvalid` (PDGID)

**Comment by 8me** [comment]
Very good idea, just a little comment about the naming convention. Should we stick to the pythonic underscore naming or rather use, e.g. `hascharm` and so on?

**Comment by tamasgal** [comment]
I'd go without underscore, that seems more Julian to me 😉 

```
julia> is
isa             isconcretetype   isfile           ismarked         ispow2           issetuid         istextmime
isabspath       isconst          isfinite         ismissing        isprimitivetype  issocket         isuppercase
isabstracttype  isdefined        isimmutable      ismount          isprint          issorted         isvalid
isapprox        isdigit          isinf            isnan            ispunct          isspace          iswritable
isascii         isdir            isinteger        isnothing        isqrt            issticky         isxdigit
isassigned      isdirpath        isinteractive    isnumeric        isreadable       isstructtype     iszero
isbits          isdispatchtuple  isless           isodd            isreadonly       issubnormal
isbitstype      isempty          isletter         isone            isready          issubset
isblockdev      isequal          islink           isopen           isreal           istaskdone
ischardev       iseven           islocked         ispath           issetequal       istaskfailed
iscntrl         isfifo           islowercase      isperm           issetgid         istaskstarted
julia> has
hasfield    hash         haskey       hasmethod    hasproperty
```

**Comment by tamasgal** [comment]
Btw. everything is happening on the [helpers](https://github.com/JuliaPhysics/Corpuscles.jl/tree/helpers) branch

**Comment by tamasgal** [comment]
I added 11 additional functions, after that we can merge!

**Comment by tamasgal** [comment]
So now we have a total of 2238 unit tests for the `helper` functions 🙈
