### ISSUE TITLE
names of charged and neutral pions are indistinguishable

### ISSUE THREAD

**Issue by jstrube** [JuliaPhysics/Corpuscles.jl#24]
Can we change the names of charged pions to "pi+" and "pi-", and the neutral pion to "pi0"?
At the moment all three are "pi".

**Comment by tamasgal** [comment]
Ah yes, that's something I wanted to address next!

Currently we use the actual name in `Base.show` and as the field `Particle.name` which corresponds to the PDG name and comes with the table produced by our SciKit-HEP colleagues: https://github.com/JuliaPhysics/Corpuscles.jl/blob/6ea2f4e43ccf0a273bd76ee020039c6c3382e8b2/data/particle2020.csv#L2

In the `particle` package, there are additional flags which are appended for the charge (plus/minus) and for "anti-ness" (tilde): https://github.com/scikit-hep/particle/blob/6fe8211181d6a0b21933b2d1042eeb4e87d77b3c/src/particle/particle/particle.py#L823

I guess we could should do this directly in the `Particle.name` upon parsing, here: https://github.com/JuliaPhysics/Corpuscles.jl/blob/6ea2f4e43ccf0a273bd76ee020039c6c3382e8b2/src/Corpuscles.jl#L206

I almost finished the helper functions which provide the corresponding information...

**Comment by tamasgal** [comment]
For the sake of completeness, this is how it looks like now (and I realise it is really time for some convenient lookup functions 😆):

```julia
julia> using Corpuscles

julia> [p for p in particles() if p.name == "pi"]
3-element Array{Particle,1}:
 Particle(211) pi
 Particle(-211) pi
 Particle(111) pi
```

**Comment by jstrube** [comment]
Actually, the problem for me comes from the fact that there isn't a nice Unicode character for all of the sub- and superscripts.
I would love to use `Unicodefun.to_latex` for all particles, but that errors for some. Using `name` for all has the lack of distinction between pions (and also protons, maybe others).
What I'm doing right now is to mix `Unicodefun.to_latex(Particle.latex)` with `Particle.name`.
`name = abs(pdg) ∈ (12, 14, 16, 130, 310, 321) ? Particle(pdg).name : to_latex(Particle(pdg).latex)`

**Comment by tamasgal** [comment]
Yep I see. I guess that the additional anti+charge flags would be a good first step.

...and then some nice convenient functions to search particles

**Comment by jstrube** [comment]
Well, would you be opposed to depending on Unicodefun?
That would make the particles much prettier

**Comment by jstrube** [comment]
One could actually avoid the dependence on unicodefun by just creating a new column on the csv with the unicode representation.

**Comment by jstrube** [comment]
The full list of PDG values where `to_latex` doesn't work is this:
```
14 16 17 18 130 310 313 315 317 319 323 325 327 329 331 335 413 415 423 425 433 435 441 445 513 515 523 525 533 535 541 555 4112 4114 4122 4132 4212 4214 4222 4224 4232 4312 4314 4322 4324 4332 4334 5112 5114 5122 5132 5222 5224 5232 5332 10311 10321 10411 10421 10431 10441 10443 10551 10553 14122 20443 20553 30313 30323 100313 100323 100441 100445 100555 104122 104312 104314 104322 104324 110551 120553 204126 9000311 9000321 9010315 9010325 9020321
```

**Comment by jstrube** [comment]
Still has a couple of bugs, but this script could be used to make a new csv file:
```
using DataFrames
using CSV
using Unicodefun
data = CSV.read("temp.csv", DataFrame)
uniString = []
for d in eachrow(data)
    name = abs(d[:ID]) ∈ [120553, 555, 10553, 310, 10441, 14122, 4122, 445, 313, 4312, 9000311, 4112, 331, 4132, 525, 415, 325, 104314, 16, 4224, 10321, 5112, 4314, 100445, 5224, 533, 5222, 425, 413, 20443, 4114, 110551, 100313, 4322, 515, 4212, 5114, 9020321, 4222, 441, 5232, 14, 10551, 323, 535, 100441, 315, 104324, 435, 17, 30323, 335, 104312, 9010325, 4324, 5132, 18, 204126, 10411, 10311, 104322, 4334, 4332, 20553, 327, 10431, 9000321, 523, 423, 329, 130, 4232, 317, 10443, 100555, 5332, 9010315, 4214, 10421, 100323, 433, 513, 319, 30313, 104122, 541, 5122] ? d[:Name] : to_latex(d[:Latex])
    push!(uniString, name)
end
data.Unicode = uniString
CSV.write("newData.csv", data)
```
(renamed it to txt here to allow upload)
[newData.txt](https://github.com/JuliaPhysics/Corpuscles.jl/files/5605320/newData.txt)

**Comment by tamasgal** [comment]
Can we make it somehow optional or so? ;) On the other hand, `Unicodefun.jl` seems to be as lightweight as a package can be: https://github.com/SimonDanisch/UnicodeFun.jl/blob/master/Project.toml 

We should add this feature into a new source file, modifying the CSV is not an option since we take them as they are from the SciKit-HEP group; so consider those as "untouchable raw data" 😅 

In https://github.com/JuliaPhysics/Corpuscles.jl/pull/23 we will put some "literals" into `literals.jl` I guess. That would be a good place for the pretty stuff, or we simply put those in `pretty.jl`?

**Comment by jstrube** [comment]
Yeah, I think Unicodefun is a pretty harmless dependency, and it's unlikely to change very fast.
Or, one could just add the CSV-conversion script to `utils/` and generate the pretty CSV every time there's a new source file from PDG.
I don't have a strong preference for where this goes. Other than the rather long list of exceptions, it's just one line of code.

**Comment by tamasgal** [comment]
I think it's easier to just hardcode those stuff in the files, it's less maintenance 😉

**Comment by tamasgal** [comment]
Do you want to take over, or should I implement it?

**Comment by jstrube** [comment]
I can do it. I'll make a pull request.

**Comment by tamasgal** [comment]
OK thanks! 🙂
