### ISSUE TITLE
interaction with Unitful is broken

### ISSUE THREAD

**Issue by jstrube** [JuliaPhysics/Corpuscles.jl#29]
I believe the units of the masses are not defined correctly.
Consider the following:
```
using NaturallyUnitful
using Corpuscles
Particle(211).mass.value + 0.5u"GeV/c^2"
```
This gives an error.
```
DimensionError: 139.57039 MeV and 0.5 GeV c^-2 are not dimensionally compatible.

Stacktrace:
 [1] +(x::Quantity{Float64, 𝐋^2 𝐌 𝐓^-2, Unitful.FreeUnits{(MeV,), 𝐋^2 𝐌 𝐓^-2, nothing}}, y::Quantity{Float64, 𝐌, Unitful.FreeUnits{(c^-2, GeV), 𝐌, nothing}})
   @ Unitful ~/.julia/packages/Unitful/JwSBO/src/quantities.jl:137
 [2] top-level scope
   @ In[64]:1
 [3] eval
   @ ./boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1090
```
The unit of mass is not MeV, however, it's MeV / c^2, regardless of whether c^2 is one or not.

**Comment by 8me** [comment]
Indeed this is not a formally correct definition of the mass unit. I seems like we were a kinda reckless when designing it and just applying the units from the PDG. Changing this should not be a big effort, but it is a breaking change so we are heading towards v2.0 ;)

**Comment by jstrube** [comment]
Works for me :-)
Thanks!

**Comment by jstrube** [comment]
Awesome, thank you.
