### ISSUE TITLE
Spin does not seem to be stored

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPhysics/Corpuscles.jl#33]
I am trying to access a spin of particle, but it does not seem to the in the structure
```julia
fieldnames(typeof(Particle(4222)))
```
gives
```julia
(:pdgid
:mass
:width
:charge
:isospin
:parity
:gparity
:cparity
:antiprop
:rank
:status
:name
:quarks
:latex
:glyph)
```

not sure what is the `rank` is

**Comment by tamasgal** [comment]
Yes, that's a bit "hidden" because it is not part of the actual dataset. The `J()` function is there:

https://github.com/JuliaPhysics/Corpuscles.jl/blob/990ac7e9427eb117c590bb74afbd42c8073c0fcd/src/helpers.jl#L452-L461

```julia
julia> p = Particle(11)
Particle(11) e

julia> J(p)
0.5

julia> p = Particle(-24)
Particle(-24) W

julia> J(p)
1.0
```

**Comment by tamasgal** [comment]
The `rank` comes from the PDG specification, it's the number of baryon stars and only used on baryons.
