### ISSUE TITLE
Conflict with Base.parse

### ISSUE THREAD

**Issue by oschulz** [JuliaPhysics/Corpuscles.jl#37]
I get a

```
WARNING: Method definition parse(Type{Base.Rational{T}}, AbstractString) where {T<:Integer} in module Base at rational.jl:98 overwritten in module Corpuscles at /user/.julia/packages/Corpuscles/0GLbd/src/Corpuscles.jl:32.
│    ** incremental compilation may be fatally broken for this module **
```

when Corpuscles.jl precompiles (Julia v1.9), because of

```julia
function Base.parse(::Type{Rational{T}}, val::AbstractString) where {T <: Integer}
```

in Corpuscles.jl:32 (which is obviously blatant type piracy :-)  ).

**Comment by tamasgal** [comment]
Ooops, did a PR shortcut... fixed in https://github.com/JuliaPhysics/Corpuscles.jl/commit/59e8c3dd620bec79ac635960d17014bcd6542f65

I'll wait for the CI and release, the local tests were fine 😉

**Comment by tamasgal** [comment]
Release 2.1.1 is on the way, containing the fix!

Thanks for reporting :)

**Comment by 8me** [comment]
> Oh yeah, let me blame @8me laughing

Susge

**Comment by oschulz** [comment]
Thanks a lot for the quick fix @tamasgal !

Now that we have Geant4.jl, there could be new interesting roles for Corpuscles.jl (PDG ID handling, etc.).

**Comment by tamasgal** [comment]
Amazing! Waiting for the issues to roll in 😆
